name: Status DEV

# runs at minute 0 of the 2rd,5th,8th and 11th hour
on:
  schedule:
    - cron:  '0 2,5,8,11 * * *'

jobs:
  dev_status_check:
    runs-on: ubuntu-latest
    env:
      URL: "https://dev.merginmaps.com/docs"
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
           url: ${{ env.URL }}

      - name: Check broken links
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: ${{ env.URL }}
          cmd_params: --buffer-size=8192 --max-connections=10 --color=always --skip-tls-verification --timeout=40 --exclude=.*twitter.com/lutraconsulting --exclude=https://download.geofabrik.de* --exclude=https://www.fauna-flora.org* --exclude=https://docs.github.com* --exclude=https://www.linkedin.com* --exclude=.*openstreetmap.org.* --exclude=.*sqlite.org.* --exclude=.*gnu.org.* --exclude=.*libtiff.org.* --exclude=https://gis.stackexchange.com/* --exclude=https://www.stackexchange.com/* # openstreetmap gives 403 for some reason?; mime duplicate parameter name for sqlite.org; TCP address timed out for GNU.org
