name: Status DEV

# runs at minute 0 of the 2rd,5th,8th and 11th hour
on:
  schedule:
    - cron:  '0 2,5,8,11 * * *'

jobs:
  dev_status_check:
    runs-on: ubuntu-latest
    env:
      URL: "https://dev.merginmaps.com/docs"
    steps:
      - uses: actions/checkout@v3
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
           url: ${{ env.URL }}

      - name: Set variables
        run: |
          EXCLUDE_LIST=$(cat scripts/broken-link-exceptions.txt)
          echo "EXCLUDE_LIST=$EXCLUDE_LIST" >> $GITHUB_ENV

      - name: Check broken links
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: ${{ env.URL }}
          cmd_params: --buffer-size=8192 --max-connections=10 --color=always --skip-tls-verification --timeout=60 ${{ env.EXCLUDE_LIST }}
